### ISSUE TITLE
Error: Cannot find module 'sonos'

### ISSUE THREAD

**Issue by joermartin** [tbouron/MMM-Sonos#1]
[23:39:56.742] [ERROR]  Error: Cannot find module 'sonos'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Sonos/node_helper.js:2:59)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Sonos/node_helper.js:141:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
[23:39:56.743] [LOG]    Whoops! There was an uncaught exception...
[23:39:56.744] [ERROR]  { Error: Cannot find module 'sonos'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Sonos/node_helper.js:2:59)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Sonos/node_helper.js:141:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10) code: 'MODULE_NOT_FOUND' }

**Comment by tbouron** [comment]
Hi @joermartin. Looks like you didn't do a `npm i` when you are inside the `MMM-Sonos` folder. Could you try that ?

**Comment by tbouron** [comment]
It also looks like my instructions are wrong, my bad. I'll fix this

**Comment by tbouron** [comment]
Fixed with https://github.com/tbouron/MMM-Sonos/commit/c7eec7cf3cd3dac6e1432083fcf21a1662d9bdcd

Please follow the [updated setup instructions](https://github.com/tbouron/MMM-FlightTracker#setup)
